# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:$PATH
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH
export PATH=$GEM_HOME/bin:$PATH
MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

export NVIM_LOG_FILE=$HOME/.vim/nvim.logs

# configure dir colors
# test -r ~/.dir_colors && eval $(dircolors ~/.dir_colors)
test -e ~/.dircolors && \
   eval `dircolors -b ~/.dircolors`

export EDITOR=nvim

# ZPlug Plugins
[ -f ~/.zsh/custom/plugins.zsh ] && source ~/.zsh/custom/plugins.zsh

# Zsh Options
[ -f ~/.zsh/custom/options.zsh ] && source ~/.zsh/custom/options.zsh

# Zsh Functions
[ -f ~/.zsh/custom/functions.zsh ] && source ~/.zsh/custom/functions.zsh

# Zsh Bindings
[ -f ~/.zsh/custom/bindings.zsh ] && source ~/.zsh/custom/bindings.zsh

# Zsh Startup
[ -f ~/.zsh/custom/startup.zsh ] && source ~/.zsh/custom/startup.zsh

# ZPlug Completions
[ -f ~/.zsh/custom/completions.zsh ] && source ~/.zsh/custom/completions.zsh

[ -f ~/.bash_aliases ] && source ~/.bash_aliases
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
if [ -f ~/.p10k.zsh ]; then
  source ~/.p10k.zsh
elif [ -f ~/.zsh/custom/p10k.zsh ]; then
  source ~/.zsh/custom/p10k.zsh
fi

brewBin="/bin/brew"
brewPrefix=
if [ -f "/home/linuxbrew/.linuxbrew$brewBin" ]; then
  brewPrefix="/home/linuxbrew/.linuxbrew"
elif [ -f "/usr/local$brewBin" ]; then
  brewPrefix="/usr/local"
fi

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

[ ! -z "$brewPrefix" ] && eval $("$brewPrefix$brewBin" shellenv)

gh=$(which gh)
[ -f $gh ] && eval $($gh completion -s zsh)

export GPG_TTY=$TTY
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
echo UPDATESTARTUPTTY | gpg-connect-agent > /dev/null
gpgconf --launch gpg-agent
